### ISSUE TITLE
Make a repo for librewolf

### ISSUE THREAD

**Issue by kzkin** [index-0/librewolf-void#18]
Could you please create a repository like [https://github.com/DAINRA/ungoogled-chromium-void](url), for easier updates ?

**Comment by index-0** [comment]
I was considering this, but I was unaware that GitHub release pages could function as the repository URL. I'll try to implement it, as this significantly simplifies matters.

**Comment by index-0** [comment]
Looks like it's all good to go. If you run into any issues, feel free to reopen the issue.

9f034c7853fb99b76c2321267edcf8331ed15e88
