### ISSUE TITLE
missing librewolf_package() function!

### ISSUE THREAD

**Issue by muezabdalla** [index-0/librewolf-void#32]
I did the same steps as the guide and also made a link to librewolf folder in the srcpkgs folder but when I run:
`./xbps-src pkg librewolf`
I get:
`=> ERROR: librewolf: missing librewolf_package() function!`

**Comment by index-0** [comment]
This happens when you make a link instead of copying the folder, use `cp -r` instead of `ln` and it should work.

**Comment by muezabdalla** [comment]
In tgat case how could i update the software
if I used git to update I will need to copy again

بتاريخ ٢٤ نوفمبر ٢٠٢٤ ٦:٤٣:١٤ م GMT+03:00، "Alfredo Pérez" ***@***.***> الرسالة:

**Comment by index-0** [comment]
You can configure a bind mount in `/etc/fstab`.

**Comment by muezabdalla** [comment]
thanks for you help I decided to make a function for updating the void-packages (xbps-src) and the normal xbps. here is the function
`
void_packages_path="$HOME/applications/void-packages/"
export SUDO="doas"
updatepackages()                                
{                                                                                               
        distro=$(uname -a | awk '{print $2}')                                                                                                                                                   
        case $distro in                                                                                                                                                                         
                void)                                                                                                                                                                           
                        $SUDO xbps-install -Su                                                                                                                                                  
                        [ ! -d "$void_packages_path" ] && return 0                                                                                                                              
                        echo "do you want to update void-packages (xbps-src)?[y/n]"
                        read ynupdate_void_packages
                        [ "$ynupdate_void_packages" != "y" ] && return 0                                                                                                                        
                        cd "$void_packages_path" || return 1                                    
                        git pull origin master                                                  
                        if [ -d "librewolf-void" ] ; then
                                rm -rf srcpkgs/librewolf                                                                                                                                        
                                cd librewolf-void/ || return 1                                                                                                                                  
                                git pull origin master                                                                                                                                          
                                cp -r srcpkgs/librewolf/ "$void_packages_path"/srcpkgs                                                                                                          
                                cd "$void_packages_path" || return 1
                        fi                                                                                                                                                                      
                        ./xbps-src update-local                                                                                                                                                 
                        ;;                                                                      
                debian)                 $SUDO apt update && $SUDO apt upgrade ;;                
                gentoo)                 $SUDO emerge --sync && $SUDO emerge -avuDN @world ;;                                                                                                    
                *)                              echo "the $distro distro is not supported" ;;
        esac                          
}
`
