### ISSUE TITLE
=> ERROR: librewolf: unknown trigger gtk-icon-cache, aborting!

### ISSUE THREAD

**Issue by levdopa** [index-0/librewolf-void#5]
Running "pip check" to verify compatibility between the system Python and the "mach" site.
=> librewolf-115.0.2_2: running post-install hook: 00-compress-info-files ...
=> librewolf-115.0.2_2: running post-install hook: 00-fixup-gir-path ...
=> librewolf-115.0.2_2: running post-install hook: 00-libdir ...
=> librewolf-115.0.2_2: running post-install hook: 00-uncompress-manpages ...
=> librewolf-115.0.2_2: running post-install hook: 01-remove-misc ...
=> librewolf-115.0.2_2: running post-install hook: 02-remove-libtool-archives ...
=> librewolf-115.0.2_2: running post-install hook: 02-remove-perl-files ...
=> librewolf-115.0.2_2: running post-install hook: 02-remove-python-bytecode-files ...
=> librewolf-115.0.2_2: running post-install hook: 03-remove-empty-dirs ...
=> librewolf-115.0.2_2: running post-install hook: 04-create-xbps-metadata-scripts ...
=> ERROR: librewolf: unknown trigger gtk-icon-cache, aborting!

**Comment by index-0** [comment]
Apologies for the delayed response. I'm unable to replicate the issue you're facing. Could you please provide more information?

1. Have you compiled the package using the latest commit of the void-packages repository?
2. Did you build the bootstrap or update it before compiling the package?

**Comment by levdopa** [comment]
Yeah I probably forgot to bootstrap it was a while ago so I forget if that was the issue
