### ISSUE TITLE
Failing to build Librewolf 117.0.1

### ISSUE THREAD

**Issue by SpidFightFR** [index-0/librewolf-void#6]
Hey, this error shows up when trying to build Librewolf:

<details>
<summary>Error when building</summary>
0:14.86 checking for sys/ioccom.h... no <br>
 0:15.20 checking for -z pack-relative-relocs option to ld... <br>
 0:15.20 DEBUG: Creating `/tmp/conftest.5t8ugrij.c` with content: <br>
 0:15.20 DEBUG: | int main() { return 0; } <br>
 0:15.20 DEBUG: | int (*ptr)() = main; <br>
 0:15.20 DEBUG: Executing: `/usr/bin/clang -std=gnu99 /tmp/conftest.5t8ugrij.c -Wl,-z,pack-relative-relocs -o  /tmp/conftest.zvf9deys -fuse-ld=lld` <br>
 0:15.20 DEBUG: Executing: `/usr/bin/readelf -d /tmp/conftest.zvf9deys` <br>
 0:15.20 Traceback (most recent call last): <br>
 0:15.20   File "/builddir/librewolf-117.0.1/configure.py", line 329, in <module> <br>
 0:15.20     sys.exit(main(sys.argv)) <br>
 0:15.20              ^^^^^^^^^^^^^^ <br> 
 0:15.20   File "/builddir/librewolf-117.0.1/configure.py", line 126, in main <br>
 0:15.20     sandbox.run(os.path.join(os.path.dirname(__file__), "moz.configure")) <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/configure/__init__.py", line 569, in run <br>
 0:15.20     func(*args) <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/configure/__init__.py", line 620, in _value_for <br>
 0:15.20     return self._value_for_depends(obj) <br>
 0:15.20            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/util.py", line 1063, in method_call <br>
 0:15.20     cache[args] = self.func(instance, *args) <br>
 0:15.20                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/configure/__init__.py", line 629, in _value_for_depends <br>
 0:15.20     value = obj.result() <br>
 0:15.20             ^^^^^^^^^^^^ <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/util.py", line 1063, in method_call <br>
 0:15.20     cache[args] = self.func(instance, *args) <br>
 0:15.20                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/configure/__init__.py", line 161, in result <br>
 0:15.20     return self._func(*resolved_args) <br>
 0:15.20            ^^^^^^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/configure/__init__.py", line 1313, in wrapped <br>
 0:15.20     return new_func(*args, **kwargs) <br>
 0:15.20            ^^^^^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/configure/__init__.py", line 912, in wrapper <br>
 0:15.20     ret = template(*args, **kwargs) <br>
 0:15.20           ^^^^^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.20   File "/builddir/librewolf-117.0.1/build/moz.configure/checks.configure", line 59, in wrapped <br>
 0:15.20     ret = func(*args, **kwargs) <br>
 0:15.20           ^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.20   File "/builddir/librewolf-117.0.1/python/mozbuild/mozbuild/configure/__init__.py", line 1313, in wrapped <br>
 0:15.21     return new_func(*args, **kwargs) <br>
 0:15.21            ^^^^^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.21   File "/builddir/librewolf-117.0.1/toolkit/moz.configure", line 1630, in pack_relative_relocs <br>
 0:15.21     needed = [l for l in dyn if l.split()[1] == "(NEEDED)"] <br>
 0:15.21              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ <br>
 0:15.21   File "/builddir/librewolf-117.0.1/toolkit/moz.configure", line 1630, in <listcomp> <br>
 0:15.21     needed = [l for l in dyn if l.split()[1] == "(NEEDED)"] <br>
 0:15.21                                 ~~~~~~~~~^^^ <br>
 0:15.21 IndexError: list index out of range <br>
 Config object not found by mach. <br>
*** Fix above errors and then restart with "./mach build" <br>
=> ERROR: librewolf-117.0.1_1: do_build: './mach build' exited with 1 <br>
=> ERROR:   in do_build() at srcpkgs/librewolf/template:241. <br>
</details>

Could you help me with that, please? :pray:

**Comment by index-0** [comment]
Looks like the following bug:
https://phabricator.services.mozilla.com/D185712

I'll commit the 117.0.1 version after testing

**Comment by SpidFightFR** [comment]
Thanks for your reply :handshake:
